SELECT * FROM customer_shopping_behavior LIMIT 10;

-- SELECT item_purchased FROM customer_shopping_behavior where customer_id = 11;
SELECT DISTINCT category FROM customer_shopping_behavior;

-- question 1 :- what is the total revenue generated by the male and female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM customer_shopping_behavior GROUP BY gender;

-- question 2 :- which customer used a discount but still spends more than avg purchase amount?
SELECT customer_id, purchase_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer_shopping_behavior
);

-- question 3 :- which are the top 5 products with the highest avg review rating?
select item_purchased, avg(review_rating) as "Average product rating" from customer_shopping_behavior GROUP BY item_purchased order by avg(review_rating) desc limit 10;

-- question 4 :- compare the avg purchase amount btw standard and express shipping
select shipping_type, ROUND(avg(purchase_amount), 2) from customer_shopping_behavior where shipping_type in ('Standard', 'Express') GROUP BY shipping_type;

-- question 5 :- Do subscribed customers spends more? calculate avg spend and total revenue betweeen subscribers and non subscribers
select subscription_status, count(customer_id) as total_customers, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue from customer_shopping_behavior GROUP BY subscription_status order BY avg_spend, total_revenue desc;

-- question 6 :- which product have the highest percentage of purchase with discount applied
SELECT
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0)
        / COUNT(*),
    2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- question 7 :- Segments customer into new, returning & loyal based on their previous purchases and show the count of each segment.
with customer_type as (sel ect customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segments from customer_shopping_behavior)
select customer_segments, count(*) as 'Number of Customers' from customer_type GROUP BY customer_segments;

-- question 8 :- what are the top 3 most purchased products withing each category?
with item_counts as(
    select category,
    item_purchased,
    count(customer_id) as total_order,
    row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from customer_shopping_behavior
    GROUP BY category, item_purchased
)
select item_rank, category, item_purchased, total_order
from item_counts
where item_rank <= 3;

-- question 9 :- Are customers who are repeat buyers(more than 5 previous purchases) are likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
GROUP BY subscription_status;

-- question 10 :- what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue from customer_shopping_behavior
GROUP BY age_group
order BY total_revenue desc;
